<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="9.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="QLNet" Version="1.13.1" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\App.Designer.cs">
      <DependentUpon>App.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Buttons.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Buttons.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Enums\CompanyTypes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CompanyTypes.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Enums\EmailTemplates.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailTemplates.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Enums\DealPhases.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DealPhases.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Enums\DealStates.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DealStates.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ErrorMessages\AppErrorMessage.it.Designer.cs">
      <DependentUpon>AppErrorMessage.it.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ErrorMessages\AppErrorMessage.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppErrorMessage.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ErrorMessages\ErrorMessageCompany.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessageCompany.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Accessory.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Accessory.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\AccessoryTypeLanguage.Designer.cs">
      <DependentUpon>AccessoryTypeLanguage.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Models\AccessoryType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AccessoryType.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\ApplicationUser.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ApplicationUser.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Article.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Article.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Company.it.Designer.cs">
      <DependentUpon>Company.it.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Models\Company.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Company.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\CompanyContract.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CompanyContract.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Contact.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Contact.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\ContractType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContractType.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\ContractTypeTicketType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ContractTypeTicketType.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\EmailTemplates.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailTemplates.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Product.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Product.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\ProductAccessoryType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductAccessoryType.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Project.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Project.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Deal.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Deal.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\Ticket.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Ticket.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\TicketModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TicketModel.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\TicketStates.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TicketStates.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\TicketType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TicketType.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\TicketTypeUser.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TicketTypeUser.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Models\UserGroupModel.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserGroupModel.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\App.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>App.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Buttons.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Buttons.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\CompanyTypes.it.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\CompanyTypes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CompanyTypes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\EmailTemplates.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EmailTemplates.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\DealPhases.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\DealPhases.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DealPhases.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\DealStates.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Enums\DealStates.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DealStates.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorMessages\AppErrorMessage.it.resx">
      <LastGenOutput>AppErrorMessage.it.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorMessages\AppErrorMessage.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppErrorMessage.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorMessages\ErrorMessageCompany.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessageCompany.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Accessory.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Accessory.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\AccessoryTypeLanguage.resx">
      <LastGenOutput>AccessoryTypeLanguage.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\AccessoryType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AccessoryType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\ApplicationUser.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\ApplicationUser.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ApplicationUser.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Article.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Article.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Article.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Company.it.resx">
      <LastGenOutput>Company.it.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Company.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Company.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\CompanyContract.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CompanyContract.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Contact.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Contact.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\ContractType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ContractType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\ContractTypeTicketType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ContractTypeTicketType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\EmailTemplates.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>EmailTemplates.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Product.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Product.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Product.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\ProductAccessoryType.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductAccessoryType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Project.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Project.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Project.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Deal.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Deal.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Ticket.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\Ticket.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Ticket.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\TicketModel.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TicketModel.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\TicketStates.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TicketStates.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\TicketType.it.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\TicketType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TicketType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\TicketTypeUser.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>TicketTypeUser.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Models\UserGroupModel.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UserGroupModel.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
  </ItemGroup>
</Project>
