//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Shared.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accepted on.
        /// </summary>
        public static string Accepted_on {
            get {
                return ResourceManager.GetString("Accepted on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Files.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Time Period.
        /// </summary>
        public static string AddTimePeriod {
            get {
                return ResourceManager.GetString("AddTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attach Document.
        /// </summary>
        public static string Allega_Documento {
            get {
                return ResourceManager.GetString("Allega Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attachments.
        /// </summary>
        public static string Allegati {
            get {
                return ResourceManager.GetString("Allegati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Any reserves must be communicated in writing within 8 days..
        /// </summary>
        public static string Any_reserves_must_be___ {
            get {
                return ResourceManager.GetString("Any reserves must be...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machine.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machines.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machines imported.
        /// </summary>
        public static string Articles_imported {
            get {
                return ResourceManager.GetString("Articles imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machines List.
        /// </summary>
        public static string ArticlesList {
            get {
                return ResourceManager.GetString("ArticlesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Artificial Intelligence.
        /// </summary>
        public static string ArtificialIntelligence {
            get {
                return ResourceManager.GetString("ArtificialIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assign the ticket.
        /// </summary>
        public static string Assegna_il_ticked_a_un_Utente {
            get {
                return ResourceManager.GetString("Assegna il ticked a un Utente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assigned.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assigned Users.
        /// </summary>
        public static string AssignedUsers {
            get {
                return ResourceManager.GetString("AssignedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assistant.
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please wait.
        /// </summary>
        public static string Attendere_prego {
            get {
                return ResourceManager.GetString("Attendere prego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attention: intervention report already present, do you want to replace it?.
        /// </summary>
        public static string AttentionReportAlreadyPresent {
            get {
                return ResourceManager.GetString("AttentionReportAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company.
        /// </summary>
        public static string Azienda {
            get {
                return ResourceManager.GetString("Azienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Companies.
        /// </summary>
        public static string Aziende {
            get {
                return ResourceManager.GetString("Aziende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Billable Time.
        /// </summary>
        public static string BillableTime {
            get {
                return ResourceManager.GetString("BillableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download.
        /// </summary>
        public static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New.
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Print.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Company .
        /// </summary>
        public static string Cancella_Azienda {
            get {
                return ResourceManager.GetString("Cancella Azienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Categories.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chat with support.
        /// </summary>
        public static string Chat_with_support {
            get {
                return ResourceManager.GetString("Chat with support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Check_your_mailbox_to_confirm_your_account {
            get {
                return ResourceManager.GetString("Check your mailbox to confirm your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Communications.
        /// </summary>
        public static string Communications {
            get {
                return ResourceManager.GetString("Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company Data.
        /// </summary>
        public static string Company_Data {
            get {
                return ResourceManager.GetString("Company Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company Name.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        public static string Conferma {
            get {
                return ResourceManager.GetString("Conferma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Confirm.
        /// </summary>
        public static string Conferma_Dati {
            get {
                return ResourceManager.GetString("Conferma Dati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm New Ticket Data.
        /// </summary>
        public static string Conferma_dati_Nuovo_Ticket {
            get {
                return ResourceManager.GetString("Conferma dati Nuovo Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create Report.
        /// </summary>
        public static string Create_Report {
            get {
                return ResourceManager.GetString("Create Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create Report?.
        /// </summary>
        public static string Create_Report_ {
            get {
                return ResourceManager.GetString("Create Report?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Customer Dashboard.
        /// </summary>
        public static string Customer_Dashboard {
            get {
                return ResourceManager.GetString("Customer Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Customer Declaration.
        /// </summary>
        public static string Customer_Declaration {
            get {
                return ResourceManager.GetString("Customer Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirmation date:.
        /// </summary>
        public static string Data_conferma_ {
            get {
                return ResourceManager.GetString("Data conferma:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expired Date.
        /// </summary>
        public static string Data_di_Scadenza {
            get {
                return ResourceManager.GetString("Data di Scadenza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date and Time.
        /// </summary>
        public static string Data_e_Ora {
            get {
                return ResourceManager.GetString("Data e Ora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Assistant.
        /// </summary>
        public static string DataAssistant {
            get {
                return ResourceManager.GetString("DataAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company Data.
        /// </summary>
        public static string Dati_Azienda {
            get {
                return ResourceManager.GetString("Dati Azienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Data.
        /// </summary>
        public static string Dati_Ticket {
            get {
                return ResourceManager.GetString("Dati Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deals.
        /// </summary>
        public static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete existing machines before import.
        /// </summary>
        public static string Delete_existing_articles_before_import {
            get {
                return ResourceManager.GetString("Delete existing articles before import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Company?.
        /// </summary>
        public static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete the intervention?.
        /// </summary>
        public static string DeleteIntervention {
            get {
                return ResourceManager.GetString("DeleteIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Product?.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Description.
        /// </summary>
        public static string Descrizione_del_Ticket {
            get {
                return ResourceManager.GetString("Descrizione del Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details {0}:.
        /// </summary>
        public static string DetailsSubTitle {
            get {
                return ResourceManager.GetString("DetailsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact Details.
        /// </summary>
        public static string Dettagli_Contatto {
            get {
                return ResourceManager.GetString("Dettagli Contatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Página{0} de {1} (total {2} registros.
        /// </summary>
        public static string Displaying_page__0__of__1___total__2__records_ {
            get {
                return ResourceManager.GetString("Displaying page {0} of {1} (total {2} records)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Distance Traveled.
        /// </summary>
        public static string Distance_Traveled {
            get {
                return ResourceManager.GetString("Distance Traveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit User.
        /// </summary>
        public static string Edit_User {
            get {
                return ResourceManager.GetString("Edit User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit {0}.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit {0}.
        /// </summary>
        public static string EditSubTitle {
            get {
                return ResourceManager.GetString("EditSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to permanently delete the company.
        /// </summary>
        public static string Eliminare_definitivamente_l_azienda {
            get {
                return ResourceManager.GetString("Eliminare definitivamente l\'azienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete machine {0}?.
        /// </summary>
        public static string Elliminare_l_articolo__0__ {
            get {
                return ResourceManager.GetString("Elliminare l\'articolo {0}?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        public static string Errore {
            get {
                return ResourceManager.GetString("Errore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connection error: {0}.
        /// </summary>
        public static string Errore_di_connessione___0_ {
            get {
                return ResourceManager.GetString("Errore di connessione: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verification error: {0}.
        /// </summary>
        public static string Errore_durante_la_verifica___0_ {
            get {
                return ResourceManager.GetString("Errore durante la verifica: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assigned.
        /// </summary>
        public static string eTicketStatesAssigned {
            get {
                return ResourceManager.GetString("eTicketStatesAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Closed.
        /// </summary>
        public static string eTicketStatesClosed {
            get {
                return ResourceManager.GetString("eTicketStatesClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Created.
        /// </summary>
        public static string eTicketStatesCreated {
            get {
                return ResourceManager.GetString("eTicketStatesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expired.
        /// </summary>
        public static string eTicketStatesExpired {
            get {
                return ResourceManager.GetString("eTicketStatesExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In progress.
        /// </summary>
        public static string eTicketStatesProcessing {
            get {
                return ResourceManager.GetString("eTicketStatesProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Event Type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expense report.
        /// </summary>
        public static string ExpenseReceipts {
            get {
                return ResourceManager.GetString("ExpenseReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signature Confirmed!.
        /// </summary>
        public static string Firma_Confermata_ {
            get {
                return ResourceManager.GetString("Firma Confermata!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signature Rejected.
        /// </summary>
        public static string Firma_Rifiutata {
            get {
                return ResourceManager.GetString("Firma Rifiutata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a for:.
        /// </summary>
        public static string for_ {
            get {
                return ResourceManager.GetString("for:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Global Settings.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have rejected the signature for intervention #{0}..
        /// </summary>
        public static string Hai_rifiutato_la_firma_per_l_intervento___0__ {
            get {
                return ResourceManager.GetString("Hai rifiutato la firma per l\'intervento #{0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a has intervened at.
        /// </summary>
        public static string has_intervened_at {
            get {
                return ResourceManager.GetString("has intervened at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The ticket has been created..
        /// </summary>
        public static string Il_Ticket_è_stato_Creato_ {
            get {
                return ResourceManager.GetString("Il Ticket è stato Creato.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import completed.
        /// </summary>
        public static string Import_completed {
            get {
                return ResourceManager.GetString("Import completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Excel.
        /// </summary>
        public static string Import_Excel {
            get {
                return ResourceManager.GetString("Import Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import failed.
        /// </summary>
        public static string Import_failed {
            get {
                return ResourceManager.GetString("Import failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Machines from Excel.
        /// </summary>
        public static string Import_Matricole_from_Excel {
            get {
                return ResourceManager.GetString("Import Matricole from Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assistances.
        /// </summary>
        public static string Interventi {
            get {
                return ResourceManager.GetString("Interventi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Services.
        /// </summary>
        public static string Interventions {
            get {
                return ResourceManager.GetString("Interventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Intervention not found..
        /// </summary>
        public static string Intervento_non_trovato_ {
            get {
                return ResourceManager.GetString("Intervento non trovato.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Knowledge Base.
        /// </summary>
        public static string KnowledgeBase {
            get {
                return ResourceManager.GetString("KnowledgeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your signature for intervention #{0} has been successfully confirmed..
        /// </summary>
        public static string La_tua_firma_per_l_intervento___0__è_stata_confermata_con_successo_ {
            get {
                return ResourceManager.GetString("La tua firma per l\'intervento #{0} è stata confermata con successo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid link. Missing token or intervention ID..
        /// </summary>
        public static string Link_non_valido__Token_o_ID_intervento_mancante_ {
            get {
                return ResourceManager.GetString("Link non valido. Token o ID intervento mancante.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Companies List.
        /// </summary>
        public static string Lista_Aziende {
            get {
                return ResourceManager.GetString("Lista Aziende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} List.
        /// </summary>
        public static string ListSubTitle {
            get {
                return ResourceManager.GetString("ListSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logs and Events.
        /// </summary>
        public static string logevents {
            get {
                return ResourceManager.GetString("logevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logos.
        /// </summary>
        public static string Logos {
            get {
                return ResourceManager.GetString("Logos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Machines/Devices.
        /// </summary>
        public static string Machines_Devices {
            get {
                return ResourceManager.GetString("Machines/Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Management of registered companies.
        /// </summary>
        public static string Manage_Companies {
            get {
                return ResourceManager.GetString("Manage Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Management.
        /// </summary>
        public static string Manage_Tickets {
            get {
                return ResourceManager.GetString("Manage Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manage your data.
        /// </summary>
        public static string Manage_your_data {
            get {
                return ResourceManager.GetString("Manage your data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minute of Intervention.
        /// </summary>
        public static string Minute_of_Intervention {
            get {
                return ResourceManager.GetString("Minute of Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string Modifica {
            get {
                return ResourceManager.GetString("Modifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Object.
        /// </summary>
        public static object Name {
            get {
                object obj = ResourceManager.GetObject("Name", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a State.
        /// </summary>
        public static string Nazione {
            get {
                return ResourceManager.GetString("Nazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No Ticket.
        /// </summary>
        public static string Nessun_Ticket {
            get {
                return ResourceManager.GetString("Nessun Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No company entered.
        /// </summary>
        public static string Nessuna_azienda_inserita {
            get {
                return ResourceManager.GetString("Nessuna azienda inserita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Message.
        /// </summary>
        public static string New_Message {
            get {
                return ResourceManager.GetString("New Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Message Received {0}.
        /// </summary>
        public static string New_Message_From {
            get {
                return ResourceManager.GetString("New Message From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Messages.
        /// </summary>
        public static string New_Messages {
            get {
                return ResourceManager.GetString("New Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Ticket.
        /// </summary>
        public static string New_Ticket {
            get {
                return ResourceManager.GetString("New Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New User.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New {0}.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New {0}.
        /// </summary>
        public static string NewSubTitle {
            get {
                return ResourceManager.GetString("NewSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description not available.
        /// </summary>
        public static string NoDescriptionAvailable {
            get {
                return ResourceManager.GetString("NoDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To be assigned.
        /// </summary>
        public static string NotAssigned {
            get {
                return ResourceManager.GetString("NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notes or Reserves.
        /// </summary>
        public static string Notes_or_Reserves {
            get {
                return ResourceManager.GetString("Notes or Reserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Ticket.
        /// </summary>
        public static string Nuovo_Ticket {
            get {
                return ResourceManager.GetString("Nuovo Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Only users assigned to the ticket can be selected. The first user is considered the primary user..
        /// </summary>
        public static string OnlyUsersAssigned {
            get {
                return ResourceManager.GetString("OnlyUsersAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open a new request.
        /// </summary>
        public static string Open_a_new_request {
            get {
                return ResourceManager.GetString("Open a new request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Our technician.
        /// </summary>
        public static string Our_technician {
            get {
                return ResourceManager.GetString("Our technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAT number.
        /// </summary>
        public static string Partita_IVA {
            get {
                return ResourceManager.GetString("Partita IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Product data.
        /// </summary>
        public static string Product_data {
            get {
                return ResourceManager.GetString("Product data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Products and Tickets.
        /// </summary>
        public static string ProductsAndTickets {
            get {
                return ResourceManager.GetString("ProductsAndTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Products Settings.
        /// </summary>
        public static string ProductsSettings {
            get {
                return ResourceManager.GetString("ProductsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Product Types.
        /// </summary>
        public static string Productstypes {
            get {
                return ResourceManager.GetString("Productstypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Product Types.
        /// </summary>
        public static string ProductTypes {
            get {
                return ResourceManager.GetString("ProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Continue.
        /// </summary>
        public static string Prosegui {
            get {
                return ResourceManager.GetString("Prosegui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You can close this window..
        /// </summary>
        public static string Puoi_chiudere_questa_finestra_ {
            get {
                return ResourceManager.GetString("Puoi chiudere questa finestra.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Push Notifications.
        /// </summary>
        public static string Push_Notifications {
            get {
                return ResourceManager.GetString("Push Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Business Name.
        /// </summary>
        public static string Ragione_Sociale {
            get {
                return ResourceManager.GetString("Ragione Sociale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Replaced and Mounted Parts.
        /// </summary>
        public static string Replaced_and_Mounted_Parts {
            get {
                return ResourceManager.GetString("Replaced and Mounted Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Requests currently handled.
        /// </summary>
        public static string Requests_currently_handled {
            get {
                return ResourceManager.GetString("Requests currently handled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Product Choice.
        /// </summary>
        public static string Scelta_del_prodotto {
            get {
                return ResourceManager.GetString("Scelta del prodotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Type Choice.
        /// </summary>
        public static string Scelta_del_Tipo_di_ticket {
            get {
                return ResourceManager.GetString("Scelta del Tipo di ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Company Choice.
        /// </summary>
        public static string Scelta_della_ditta {
            get {
                return ResourceManager.GetString("Scelta della ditta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If you believe this is an error, please contact our office..
        /// </summary>
        public static string Se_ritieni_che_ci_sia_stato_un_errore__contatta_il_nostro_ufficio_ {
            get {
                return ResourceManager.GetString("Se ritieni che ci sia stato un errore, contatta il nostro ufficio.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the machine.
        /// </summary>
        public static string Select_the_article {
            get {
                return ResourceManager.GetString("Select the article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the Client.
        /// </summary>
        public static string Select_the_Client {
            get {
                return ResourceManager.GetString("Select the Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the Product.
        /// </summary>
        public static string Select_the_product {
            get {
                return ResourceManager.GetString("Select the product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the type of Ticket.
        /// </summary>
        public static string Select_the_type_of_Ticket {
            get {
                return ResourceManager.GetString("Select the type of Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select a Product.
        /// </summary>
        public static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose.
        /// </summary>
        public static string Seleziona {
            get {
                return ResourceManager.GetString("Seleziona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the Company....
        /// </summary>
        public static string Seleziona_la_Ditta___ {
            get {
                return ResourceManager.GetString("Seleziona la Ditta...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service began.
        /// </summary>
        public static string Service_began {
            get {
                return ResourceManager.GetString("Service began", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service ended.
        /// </summary>
        public static string Service_ended {
            get {
                return ResourceManager.GetString("Service ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service Types.
        /// </summary>
        public static string ServiceTypes {
            get {
                return ResourceManager.GetString("ServiceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the date of the event.
        /// </summary>
        public static string Set_the_date_of_the_event {
            get {
                return ResourceManager.GetString("Set the date of the event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the time of the event.
        /// </summary>
        public static string Set_the_time_of_the_event {
            get {
                return ResourceManager.GetString("Set the time of the event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configure and manage all CRM settings.
        /// </summary>
        public static string SettingsListSubTitle {
            get {
                return ResourceManager.GetString("SettingsListSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TICKETS History.
        /// </summary>
        public static string Storico_TICKETS {
            get {
                return ResourceManager.GetString("Storico TICKETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Settings.
        /// </summary>
        public static string System_Settings {
            get {
                return ResourceManager.GetString("System Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System Configuration.
        /// </summary>
        public static string SystemConfiguration {
            get {
                return ResourceManager.GetString("SystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The customer authorizes the processing of personal data in accordance with current regulations..
        /// </summary>
        public static string The_customer_authorizes___ {
            get {
                return ResourceManager.GetString("The customer authorizes...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The customer declares that the intervention has been completed satisfactorily..
        /// </summary>
        public static string The_customer_declares___ {
            get {
                return ResourceManager.GetString("The customer declares...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The description must be at least 10 characters long.
        /// </summary>
        public static string The_description_must_be_at_least_10_characters_long {
            get {
                return ResourceManager.GetString("The description must be at least 10 characters long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The undersigned declares to have received the service as described above..
        /// </summary>
        public static string The_undersigned_declares___ {
            get {
                return ResourceManager.GetString("The undersigned declares...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tick if no comments.
        /// </summary>
        public static string Tick_if_no_comments {
            get {
                return ResourceManager.GetString("Tick if no comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket #.
        /// </summary>
        public static string Ticket__ {
            get {
                return ResourceManager.GetString("Ticket #", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Edit.
        /// </summary>
        public static string Ticket_Edit {
            get {
                return ResourceManager.GetString("Ticket Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Feedbacks.
        /// </summary>
        public static string Ticketfeedbacks {
            get {
                return ResourceManager.GetString("Ticketfeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Management.
        /// </summary>
        public static string TicketManagement {
            get {
                return ResourceManager.GetString("TicketManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Number.
        /// </summary>
        public static string TicketNumber {
            get {
                return ResourceManager.GetString("TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TICKETS in progress.
        /// </summary>
        public static string TICKETS_in_Lavorazione {
            get {
                return ResourceManager.GetString("TICKETS in Lavorazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tickets in Process.
        /// </summary>
        public static string Tickets_in_Process {
            get {
                return ResourceManager.GetString("Tickets in Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket States.
        /// </summary>
        public static string TicketStates {
            get {
                return ResourceManager.GetString("TicketStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket types.
        /// </summary>
        public static string Tickettypes {
            get {
                return ResourceManager.GetString("Tickettypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ticket Type Translates.
        /// </summary>
        public static string Tickettypeslanguages {
            get {
                return ResourceManager.GetString("Tickettypeslanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To be invoiced.
        /// </summary>
        public static string ToBeInvoiced {
            get {
                return ResourceManager.GetString("ToBeInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid or already used token..
        /// </summary>
        public static string Token_non_valido_o_già_utilizzato_ {
            get {
                return ResourceManager.GetString("Token non valido o già utilizzato.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total (hh:mm).
        /// </summary>
        public static string Total_Intervention_Time {
            get {
                return ResourceManager.GetString("Total Intervention Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total Billable Minutes.
        /// </summary>
        public static string TotalBillableMinutes {
            get {
                return ResourceManager.GetString("TotalBillableMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total Kilometers.
        /// </summary>
        public static string TotalKilometers {
            get {
                return ResourceManager.GetString("TotalKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total Travel Minutes.
        /// </summary>
        public static string TotalTravelMinutes {
            get {
                return ResourceManager.GetString("TotalTravelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total Work Minutes.
        /// </summary>
        public static string TotalWorkMinutes {
            get {
                return ResourceManager.GetString("TotalWorkMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Travel Time.
        /// </summary>
        public static string TravelTime {
            get {
                return ResourceManager.GetString("TravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updated Data.
        /// </summary>
        public static string UpdatedData {
            get {
                return ResourceManager.GetString("UpdatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Management.
        /// </summary>
        public static string UtentiListSubTitle {
            get {
                return ResourceManager.GetString("UtentiListSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAT ID.
        /// </summary>
        public static string VAT_ID {
            get {
                return ResourceManager.GetString("VAT ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signature verification in progress....
        /// </summary>
        public static string Verifica_firma_in_corso___ {
            get {
                return ResourceManager.GetString("Verifica firma in corso...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verification in progress....
        /// </summary>
        public static string Verifica_in_corso___ {
            get {
                return ResourceManager.GetString("Verifica in corso...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View all tickets.
        /// </summary>
        public static string View_all_tickets {
            get {
                return ResourceManager.GetString("View all tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View Report.
        /// </summary>
        public static string View_Report {
            get {
                return ResourceManager.GetString("View Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View your products.
        /// </summary>
        public static string View_your_products {
            get {
                return ResourceManager.GetString("View your products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Private.
        /// </summary>
        public static string VisibilityPrivate {
            get {
                return ResourceManager.GetString("VisibilityPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome to your support portal.
        /// </summary>
        public static string Welcome_to_your_support_portal {
            get {
                return ResourceManager.GetString("Welcome to your support portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In Progress.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Work Time.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ZIP.
        /// </summary>
        public static string ZIP {
            get {
                return ResourceManager.GetString("ZIP", resourceCulture);
            }
        }
    }
}
